apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o deployments/
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: celery-worker
  name: celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: celery-worker
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o deployments/
        kompose.version: 1.27.0 (b0ed6a2c9)
      creationTimestamp: null
      labels:
        io.kompose.service: celery-worker
    spec:
      containers:
        - args:
            - celery
            - -A
            - tasks
            - worker
            - --loglevel=info
          image: chitramai/kube-celery-dev-fork_celery_worker
          name: celery-worker 
          imagePullPolicy: IfNotPresent
          resources: {}
        - args:
            - celery
            - -A
            - tasks.app
            - flower
            - --port=5555
          env:
            - name: CELERY_BROKER_URL
              value: redis://redis:6379/0
            - name: CELERY_RESULT_BACKEND
              value: redis://redis:6379/0
          image: chitramai/kube-celery-dev-fork_flower 
          name: flower
          ports:
            - containerPort: 5555
      restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o deployments/
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: flower
  name: flower
spec:
  ports:
    - name: "5556"
      port: 5556
      targetPort: 5555
  selector:
    io.kompose.service: flower
status:
  loadBalancer: {}