apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: celery
  labels:
    name: celery-deployment
    app: celery-worker
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      name: celery-deployment
      app: celery-worker
  template: 
    metadata: 
      name: celery
      labels: 
        name: celery-deployment
        app: celery-worker
    spec: 
      containers: 
      - name: celery
        image: chitramai/kube-celery-dev-fork_celery_worker
        args:
          - celery
          - -A
          - tasks
          - worker
          - --loglevel=info
        env:
          - name: CELERY_BROKER_URL
            value: redis://redis:6379/0
          - name: CELERY_RESULT_BACKEND
            value: redis://redis:6379/0
        
# ---
# apiVersion: v1
# kind: Service
# metadata: 
#   name: celery
#   labels:   
#     name: celery-pod-service
# spec: 
#   type: ClusterIP
#   ports: 
#   - targetPort: 6379
#     port: 80
#   selector: 
#     name: celery-deployment
#     app: celery-worker

  
