apiVersion: v1
kind: Pod
metadata: 
  name: flask-application 
  labels: 
    name: flask-application-pod
    app: celery-worker
spec: 
  containers: 
  - name: celery-flask-app
    image: chitramai/kube-celery-dev-fork_flask_application:latest
    args:
      - flask
      - run
      - --host=0.0.0.0
    env:
      - name: MONGODB_HOST
        value: mongodb
      - name: MONGODB_PORT
        value: "27017"
      - name: REDIS_PORT
        value: "6379"
      - name: REDIS_URL
        value: redis

---
apiVersion: v1
kind: Service
metadata: 
  name: flask-service
  labels: 
    name: flask-pod-service
spec: 
  type: ClusterIP
  ports: 
    - name: "5000"
      port: 5000
      targetPort: 80
  selector: 
    name: flask-application-pod
    app: celery-worker